apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:HJHgJFZ7r3tT1ajGwKtKu+fPvfaVoQwExg==,iv:aMsjMNeZYwiLh0lOttyDZ1Bfw7Ub2dYp4R0fFVLJc3A=,tag:seNoedEgWL/uH5LWEB9idw==,type:str]
sops:
    lastmodified: "2025-10-05T16:20:18Z"
    mac: ENC[AES256_GCM,data:pkPvjtVb6Y9oi7FOA8L3FW7dHxKyw8o0g+AOvHFsSv/+0z5Rf0LeZTyd+x+cXPunH0ViWXpXLGYPSN4lviLsVaAVkIJN7hdK7GlCjN+T8LyuunsPw5T8RssRmEoczjh+jIy2m+VCrGm/K8RCvhAuUHplDpm0ogTXCk9DjLoC1Uo=,iv:pNa4DPdc1S/MPYdA6eMkIgFEyOqDi9mOfCyJuusXta8=,tag:rM0d5HdMYtLvZmhP+K9Dmw==,type:str]
    pgp:
        - created_at: "2025-10-05T16:20:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAwuhE/FALPwkAQv/SzCu0PsEL3LvXkLV2q8JQ61XTj/GyQe54ubvnTjnn8Iv
            Szpl9ICWcMhsGXrLdPi8sq5WV6q4RGfayxVLmJpvSrymm0pIKwty96W7PmZZkk1p
            /wQgBvXLpsWCQN7GPFlcVGprABUzQoPedcG9KHCDbTvcFAo56Ihz6mFffybGqDV+
            /n3Ts6Y1BZY3jcK1WS91CaQ1PX7exvno8jQnCSzGMe88/HV4lHvriPYAO0aE9h1C
            Y9pmWalecW3w4eT53549koTgTtAfhKD5Zb2UuEl4mEf/ur6Gp9JMlCMZUbxyO3v3
            T2w+2kHkPB4EQRbk9mm1AwmxmPTB0LbRmA4RLNkLu3bH94JhkUjeJGwPocA5r3UU
            kovN+yzr38Qg++2+8iYFxtHFFfgYH43pBb8vTMOoyVkYAb04yABrSGwR8SYgkGi2
            cXqwB6tBvgQsTVgAkWxZokH9X3bC/VvRgU54nGPoNBxEUeSnsVvqdI38R5HCotWK
            8MkRWOtVO9yMejWnlTZ21GgBCQIQDdDhaGKO1sh9xMhDH02QvJBVxNHO5KKTNW/S
            WPMcjK7QoXLzWjO+kBUfqj9h8Do2GCTl6VEMl/04WuJK3ezIFg1LxWrRg/xuEQyB
            QgY03BGXUJS5xtssVcQ8eArwqCt/W715pQ==
            =ekrX
            -----END PGP MESSAGE-----
          fp: 5AF6EE35577002BD
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
